config/routes.rb
Rails.application.routes.draw do

  root "ripples#index"

  get '/ripples/next10', to: 'ripples#next10'
  get '/ripples/previous10', to: 'ripples#previous10'
  get '/ripples/oldest', to: 'ripples#oldest'
  get '/ripples/newest', to: 'ripples#newest'
  resources :ripples

end

app/models/ripple.rb
class Ripple < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ripples_controller.rb
class RipplesController < ApplicationController
  before_action :set_ripple, only: [:show]

  # GET /ripples
  # GET /ripples.json
  def index
    session[:page] ||= 0 
    @ripples = Ripple.order(created_at: :desc)
    first_displayed_record = session[:page] * 10
    last_displayed_record = first_displayed_record + 9
    total_pages = @ripples.count % 10

    @ripples = @ripples[first_displayed_record..last_displayed_record]
  end

  def next10
    total_ripples = Ripple.all.count
      if ((total_ripples % 10) == 0)
     	 total_pages = total_ripples / 10
    else
        total_pages = total_ripples / 10 + 1
    end
    if session[:page] < total_pages - 1
      session[:page] += 1
      respond_to do |format|
        format.html { redirect_to ripples_url }
        format.json { head :no_content }
      end
    else
      self.oldest
    end
  end

  def previous10
    if session[:page] > 0
      session[:page] -= 1
      respond_to do |format|
        format.html { redirect_to ripples_url }
        format.json { head :no_content }
      end
    else
      self.newest
    end
  end

  def oldest
    total_ripples = Ripple.all.count
    if ((total_ripples % 10) == 0)
      total_pages = (total_ripples / 10) 
    else
      total_pages = total_ripples / 10 + 1
    end
    session[:page] = total_pages - 1
    Ripple.order(created_at: :asc)
    respond_to do |format|
      format.html { redirect_to ripples_url }
      format.json { head :no_content }
    end	
  end

  def newest
    session[:page] = 0
    Ripple.order(created_at: :desc)
    respond_to do |format|
      format.html { redirect_to ripples_url }
      format.json { head :no_content }
    end	
  end

  # GET /ripples/1
  # GET /ripples/1.json
  def show
  end

  # GET /ripples/new
  def new
    @ripple = Ripple.new
  end

  # POST /ripples
  # POST /ripples.json
  def create
    @ripple = Ripple.new(ripple_params)

    respond_to do |format|
      if @ripple.save
        format.html { redirect_to ripples_url }
        format.json { render :show, status: :created, location: @ripple }
      else
        format.html { render :new }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ripple
      @ripple = Ripple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ripple_params
      params.require(:ripple).permit(:username, :username_url, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ripples_helper.rb
module RipplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consciousmess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <h1 class="bannerMargin">CONSCIOUS/mess</h1>
    <h2 class="bannerMargin">...a stream of anonymous online ramblings</h2>
  </div>

<%= yield %>

</body>
</html>

app/views/ripples/_form.html.erb
<%= form_for(@ripple) do |f| %>
  <% if @ripple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ripple.errors.count, "error") %> prohibited this ripple from being saved:</h2>

      <ul>
      <% @ripple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :username_url %><br>
    <%= f.text_field :username_url %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message, :size=>"100x20" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ripples/index.html.erb
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Username url</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ripples.each do |ripple| %> 
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <% if ripple.username_url == "" %>
          <td><%= ripple.username %></td>
        <% else %>
          <td><%= link_to ripple.username, ripple.username_url %></td>
        <% end %>
        <td><%= ripple.message %></td>
	<td><%= ripple.created_at %></td>
        <td><%= link_to 'Show', ripple %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if session[:page] == 0 %>
  Newest|Previous 10 Ripples|
<% else %>
  <%= link_to 'Newest', '/ripples/newest' %>| 
  <%= link_to 'Previous 10 Ripples', '/ripples/previous10' %>|
<% end %>
<% if session[:page] >= Ripple.all.count/10 %>
  Next 10 Ripples|Oldest|
<% else %>
  <%= link_to 'Next 10 Ripples', '/ripples/next10' %>| 
  <%= link_to 'Oldest', '/ripples/oldest' %>|
<% end %>
<%= link_to 'New Ripple', new_ripple_path %>

app/views/ripples/new.html.erb
<h1>New ripple</h1>

<%= render 'form' %>

<%= link_to 'Back', ripples_path %>

app/views/ripples/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="username_format">
  <% if @ripple.username_url == "" %> 
    <td><%= @ripple.username %> said...</td>
  <% else %>
    <td><%= link_to @ripple.username, @ripple.username_url %> said...</td>
  <% end %>
</h2>

<p class="message_format">
  <%= @ripple.message %>
</p>

<%= link_to 'Back', ripples_path %>